services:
  reverse-proxy:
    image: traefik:v2.11.8
    container_name: traefik-orchestrator
    restart: always
    env_file:
      - cloudflare.env
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - traefik-bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik:/etc/traefik

networks:
  traefik-bridge:
    external: true
