services:
  socket-proxy:
    image: wollomatic/socket-proxy:1
    user: 65534:992 # stat -c '%g' /var/run/docker.sock
    read_only: true
    cap_drop:
      - ALL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy
    command:
      - '-loglevel=info'
      - '-listenip=0.0.0.0'
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|services.*|tasks.*|networks.*|events.*|nodes.*)'
      - '-allowHEAD=/_ping'
      - '-stoponwatchdog'
      - '-shutdowngracetime=5'
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          memory: 64M
      placement:
        constraints:
          - node.role == manager

  reverse-proxy:
    image: traefik:v3.7
    env_file:
      - cloudflare.env
    environment:
      - DOCKER_HOST="tcp://socket-proxy:2375"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: udp
        mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - socket-proxy
      - traefik-bridge
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - type: bind
        source: ./dynamic
        target: /etc/traefik/dynamic
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: ./acme
        target: /etc/traefik/acme
        bind:
          create_host_path: true
      - type: bind
        source: ./logs
        target: /etc/traefik/logs
        bind:
          create_host_path: true
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.routers.dashboard.rule=Host(`traefik.local`)
        - traefik.http.routers.dashboard.entrypoints=web,websecure
        - traefik.http.routers.dashboard.tls=true
        - traefik.http.routers.dashboard.service=api@internal
        - traefik.http.routers.dashboard.middlewares=localnetwork@file

networks:
  socket-proxy:
    driver: overlay
    internal: true
  traefik-bridge:
    external: true
